language: python
python: "3.4"
install:
  - "pip install -r requirements.txt"
  - "pip install pep8 pyflakes"
before_script:
  - "pep8 --ignore E501,E702 lje.py"
script:
  - "python lje.py init new.db"
  - "python lje.py import tubmlr eigenein.tumblr.com imported.db"
  - "python lje.py build imported.db build"
